env:
  global:
    - secure: FRfDKMlUDo9kC8d4g755ZJS02jjzydD0g3ryZEKepyXQy5ePM1W0DD72HZiI93C49S4rRp3Y/zIGudr7esUMU+a7Jca+4cwXb9TFeZz0B+QLG3G0xr+nUVYJWs15i2QkMEV2DRXd/mm2iUtAdnj9kbXvLVzF/Em8nqYfNk4HSvkg3LstKlMcW+eSXP3oFSOQ2jP5d5OuQxhUfLlmwnZJwvb6tnM48il49MBW3CwFmo8VoF2Vkof1yPex+Fa9LuAv2qisx8GjSTejtz6VUye3EbnVf5Cn7bCCXgIOngytdc0WWAOS7jG5VStDD50O7WISYmkzhnJQ+UYagxCXN+ButdiqZqrf5Bp6gN7VuZKPcKYeYC6mRvMU59cERTNGYVqzENtl2p55XT4/D4P1laVEyzntHS45anVQmw0iwpD27W+1iafhaE27PI1MTxejQbsYw8dHsKw+myEtpnLgoT4Zc0W97TlY/SecrGMbLHAYz3o7+gOEJlAlc7XX+FqRahv7vMJOAy63z8Y8PxpyxKbQhSn2RA7kX4F7W1ZJQ/wOOk+7+ov7pe7v5bV/2/2UqkcUXbsylHeIWiQB+jXK9g8D0y3aiVc8oh9jAXfcOPhcCfGSdtandxA7YggOY0y5pnOy8p4tEXDb5B2hHI+E5hsPv66UY8SvuSEfBT3svWnGl0Y=

language: node_js
node_js:
  - "8.7"
branches:
  only:
    - master

before_deploy:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - ng build --prod

deploy:
  provider: firebase
  token:
    secure: FRfDKMlUDo9kC8d4g755ZJS02jjzydD0g3ryZEKepyXQy5ePM1W0DD72HZiI93C49S4rRp3Y/zIGudr7esUMU+a7Jca+4cwXb9TFeZz0B+QLG3G0xr+nUVYJWs15i2QkMEV2DRXd/mm2iUtAdnj9kbXvLVzF/Em8nqYfNk4HSvkg3LstKlMcW+eSXP3oFSOQ2jP5d5OuQxhUfLlmwnZJwvb6tnM48il49MBW3CwFmo8VoF2Vkof1yPex+Fa9LuAv2qisx8GjSTejtz6VUye3EbnVf5Cn7bCCXgIOngytdc0WWAOS7jG5VStDD50O7WISYmkzhnJQ+UYagxCXN+ButdiqZqrf5Bp6gN7VuZKPcKYeYC6mRvMU59cERTNGYVqzENtl2p55XT4/D4P1laVEyzntHS45anVQmw0iwpD27W+1iafhaE27PI1MTxejQbsYw8dHsKw+myEtpnLgoT4Zc0W97TlY/SecrGMbLHAYz3o7+gOEJlAlc7XX+FqRahv7vMJOAy63z8Y8PxpyxKbQhSn2RA7kX4F7W1ZJQ/wOOk+7+ov7pe7v5bV/2/2UqkcUXbsylHeIWiQB+jXK9g8D0y3aiVc8oh9jAXfcOPhcCfGSdtandxA7YggOY0y5pnOy8p4tEXDb5B2hHI+E5hsPv66UY8SvuSEfBT3svWnGl0Y=
  project: robot-stage-1
